/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Acces (
  /* ID interne de la ressource */
  id: Option[Int],
  /* IdTransverse de l'objet. */
  idTransverse: String,
  /* type d'accès (FTTH/ADSL/FTTB/VDSL). */
  `type`: AccesEnums.&#x60;Type&#x60;,
  /* ID d’éligibilité (Id R@ ou Id India) */
  idEligibilite: Option[String],
  /* Débit de l’accès à commander */
  debit: Option[String],
  /* Obligatoire si type=xDSL sinon vide.Valeurs autorisées (1,2,3 ou null . 1=TOTAL, 2=CONSTRUCTION,3=PARTIEL). */
  typedegroupage: Option[Double]
) extends ApiModel

object AccesEnums {

  type &#x60;Type&#x60; = &#x60;Type&#x60;.Value
  object &#x60;Type&#x60; extends Enumeration {
    val FTTH = Value("FTTH")
    val DSL = Value("DSL")
  }

}

