/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Commande (
  /* Id transverse */
  idTransverse: String,
  /* type de l'acces */
  confVpn: Any,
  /* Objet  accès. */
  acces: Any,
  /* ID d’éligibilité (Id R@ ou Id India) */
  poste: Any
) extends ApiModel


