/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Poste (
  /* Id transverse */
  idTransverse: String,
  /* Numéro de Désignation d’Installation */
  ndi: String,
  /* Relevé d’Information Opérateur.Facilite l'identification de la ligne lors des demandes de portabilité du numéro. */
  rio: String,
  /* Donnée indiquant si le « ndi » est à porter sur le réseau SFR. */
  porte: String,
  /* Nom de l’utilisateur. */
  nom: String,
  /* Prénom de l’utilisateur. */
  prenom: String,
  /* Identifiant utilisateur finale. */
  idufe: String
) extends ApiModel


